feat(markdown-docx): add codeblock transformer - #397
accordproject/markdown-transform pull request #430
Opened 2021-07-24 07:42 UTC by K-Kumar-01

Signed-off-by: k-kumar-01 <kushalkumargupta4@gmail.com>

Improves transformer by allowing `codeblock transformation from `OOXML` to `CiceroMark` and vice-versa.

### Changes

- Add transformation logic: OOXML <-> CiceroMark
- Add rules
- Add test

### Screenshots or Video

![ecbb9cfc-10d1-4512-88c2-5806edaf061c](https://user-images.githubusercontent.com/59891164/126861315-23716c78-26d5-4a29-9ea4-b25abe435d51.jpeg)

### Author Checklist
- [x] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [x] Vital features and changes captured in unit and/or integration tests
- [x] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [ ] Extend the documentation, if necessary
- [ ] Merging to `master` from `fork:branchname`

2021-07-26 09:05 UTC, algomaster99 reviewed
Tried to run your code and found that it doesn't parse the literal `\\n`. Here is a failing test case:
```json
{
  "$class": "org.accordproject.commonmark.Document",
  "xmlns": "http://commonmark.org/xml/1.0",
  "nodes": [
    {
      "$class": "org.accordproject.templatemark.ContractDefinition",
      "name": "top",
      "nodes": [
        {
          "$class": "org.accordproject.commonmark.CodeBlock",
          "text": "cout<<\"\\n\";\n"
        }
      ]
    }
  ]
}
```

2021-07-26 10:24 UTC, K-Kumar-01 commented
> Tried to run your code and found that it doesn't parse the literal `\\n`. Here is a failing test case:
> 
> ```json
> {
>   "$class": "org.accordproject.commonmark.Document",
>   "xmlns": "http://commonmark.org/xml/1.0",
>   "nodes": [
>     {
>       "$class": "org.accordproject.templatemark.ContractDefinition",
>       "name": "top",
>       "nodes": [
>         {
>           "$class": "org.accordproject.commonmark.CodeBlock",
>           "text": "cout<<\"\\n\";\n"
>         }
>       ]
>     }
>   ]
> }
> ```

I don't think this would be necessary as the transformer will be used by lawyers primarily and won't generally use `\n` in contracts. 
@dselman Could you please tell if this is necessary?

2021-07-27 10:43 UTC, algomaster99 commented
@dselman Could you let us know if contracts have escape sequences, like `\n`, in code blocks? Currently, when we encounter `\n` while parsing a codeblock, we convert it to a linebreak. However, `\\n` is also treated as a line break even though it is literally `\n`, for example `\n` in `cout<<"\n";`. @K-Kumar-01 is arguing that we don't need to parse this literal as it would never be used in contracts. I think if ciceromark_parsed transformer is able to distinguish then our transformer should be capable too.

2021-08-02 08:51 UTC, dselman commented on packages/markdown-docx/src/ToCiceroMarkVisitor.js
> +     * Checks if the node is a thematic break or not
Typo? This doesn't seem to be related to a thematic break?

2021-08-02 08:54 UTC, dselman requested changes
Once the typo in the JSDoc is fixed I will merge.

2021-08-02 10:07 UTC, K-Kumar-01 commented
@dselman 
Made the changes.
Let me know if there is anything else required.

2021-08-03 10:06 UTC, algomaster99 approved these changes
Looks good to me!

2021-08-03 10:06 UTC, merged